### ISSUE TITLE
Is the library is no longer accessible ?

### ISSUE THREAD

**Issue by Demos25** [phantom-sea-limited/H#2]
RIP then

**Comment by Rcrwrate** [comment]
Due to china's policy update.
We have to close the service in china, but now you can access it by another service **which Served by an anonymous third party.**
[here is the domain.](https://book.deception.world/)
[onion domain](http://p7pto2bh5442s5dowbcl2qyz6xdonipcbkj62hyqhr55px6rdbps3rad.onion/)
Also, We will soon keep the main code open source ,with the main access_token(can update by access our API server)

**Comment by Rcrwrate** [comment]
@Demos25 
new repository here

**Comment by Demos25** [comment]
Ok thanks for your answer. It's no wonder that so many sites were taken down for the last weeks. It's OK to hide the reply.
